//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hospital_DBEntities : DbContext
    {
        public Hospital_DBEntities()
            : base("name=Hospital_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Out_Door> Out_Door { get; set; }
        public virtual DbSet<Tbl_Patient> Tbl_Patient { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_Docter> Tbl_Docter { get; set; }
        public virtual DbSet<Tbl_Indoor> Tbl_Indoor { get; set; }
        public virtual DbSet<Tbl_MasterPathology> Tbl_MasterPathology { get; set; }
        public virtual DbSet<Tbl_PathologyTest> Tbl_PathologyTest { get; set; }

        public System.Data.Entity.DbSet<Hospital_Management.Models.OutDoor> OutDoors { get; set; }
    }
}
