//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PathologyTest
    {
        public int Id { get; set; }
        public string Test_id { get; set; }
        public string Test_Name { get; set; }
        public string Paitent_Id { get; set; }
        public string Outdoor_Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Test_by { get; set; }
    }
}
