//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Indoor
    {
        public int Id { get; set; }
        public string Record_No { get; set; }
        public string OutDoorID { get; set; }
        public string PaitentId { get; set; }
        public Nullable<System.DateTime> Admiction_Date { get; set; }
        public string Cabin_No { get; set; }
        public string OutDoorDocter { get; set; }
        public string Consoltant_Docter { get; set; }
        public string INdoor_No { get; set; }
        public string Provisional_deg { get; set; }
        public string Comment { get; set; }
        public string Paitent_Name { get; set; }
        public Nullable<System.DateTime> Date_Opperaton { get; set; }
        public string Sex { get; set; }
    }
}
