//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterPathology
    {
        public int Id { get; set; }
        public string Test_Name { get; set; }
        public Nullable<int> Ammout { get; set; }
        public string Requard_time { get; set; }
        public string Tset_ID { get; set; }
        public string Type { get; set; }
        public bool status { get; set; }
    }
}
